### PR TITLE
Changes to high level consumer

### PR DESCRIPTION
**Pull request by shmish111**
It is not expected that this PR be accepted, it's more of an example of what I required to implement a manifold consumer.  Basically extracting the getting of a KafkaStream from the messages function.

The lazy seq wrapper has been moved out and a manifold async example created.

It is not expected that the manifold client be left in as clj-kafka is probably better off doing as little as possible.  I guess it would be nice as a library user to be able to create my own high level consumer using manifold, core.async or whatever I want as in clj-kafka.consumer.manifold.

### CODE REVIEW

**Comment by shmish111** [comment]
One question, do you envisage the supporting libs as completely separate projects, e.g. `clj-kafka-manifold` and `clojure-kafka-coreasync`?

**Comment by shmish111** [comment]
And so do you mean put the `messages` function back in, rather than have it in it's own ns `clj-kafka.consumer.seq`?  It's just that I saw it as something on the same level as a manifold stream and although it wouldn't need a separate project, it could still live in a separate ns.  The ns then serves as a sort of reference as to how you would go about implementing something else?

**Comment by shmish111** [comment]
I've created a separate project, https://github.com/shmish111/manifold-kafka which this PR enables.  One problem I had was that for the tests I had to copy/paste the test utils ns, not sure how you can best make that available to other libraries?  How is this PR now, considering it is to enable other projects to extend clj-kafka...

**Comment by shmish111** [comment]
Hi, I don't suppose you have had chance to think about this PR?  Although I created a separate ns for seq (and screwed all the formatting with cursive) the essence is having access to the `KafkaStream` in the consumer.  With access to this you can create your own abstractions such as the manifold channel I want to...

**Comment by pingles** [comment]
Hi David,

Really sorry, I haven't had a chance to look yet- I'll see if I can get a
chance this afternoon or tomorrow.

**Comment by shmish111** [comment]
Hi, sorry to ask again but any chance of looking at this, I've got forked clj-kafka hanging around my project I want to get rid of :-)

**Comment by pingles** [comment]
Don't be sorry- thank you for the reminder, I'll try and take a look today
and this week.

**Comment by pingles** [comment]
Hi,

I've started working on some changes for a 0.3 release. A lot of other PRs were similar in wanting easier access to the underlying API.

Could you take a look at https://github.com/pingles/clj-kafka/blob/master/src/clj_kafka/consumer/zk.clj now and see if it is in better shape to support your extra lib for connecting to manifold?

If so I'll probably tidy a few other things up then push a 0.3 release to Clojars that you could depend on.

Thanks for your patience!!

Paul

**Comment by shmish111** [comment]
Looks cool, the only thing I would add is that since the most common use
case is to provide 1 topic then it's nice to have a function that returns
the stream for that topic, like the `messages` function but without using
`stream-seq`.

**Comment by pingles** [comment]
I think that probably would be pretty convenient, but, I'd rather leave that to clients- currently it means all the special 1 stream/1 thread stuff just lives inside the higher-level `messages` function?

**Comment by pingles** [comment]
I hope it's ok but I'm going to close this PR for now- I'm going to release the current master as 0.3.0 to Clojars so you should be able to update your manifold adapter to depend on this release.

Thanks for your help and suggestions!

**Comment by shmish111** [comment]
Sure, well it will work for me thanks :)

**Comment by shmish111** [comment]
FYI I managed to get my little library done now https://github.com/shmish111/manifold-kafka

**Comment by pingles** [comment]
Cool! Glad we got there in the end :)

**Pull request closed without merging**
