### PR TITLE
Added feature to access Kafka's built-in consumer offset management

### PR DESCRIPTION
**Pull request by ooasis**
Hi Paul,

This library is pretty handy for quick hacking.  I have recently added a new feature so that I can use it to view and reset Kafka built-in offsets.  If you have time, please take a look.  I also update the documentation and the test code to show how it can be used.

Regards,

Hang

### CODE REVIEW

**Comment by pingles** [comment]
Thanks for the pull request- we'll take a look soon.

We already had a few functions to read the offset data directly from ZooKeeper but i guess this is more in line with Kafka's progression to pushing more of that into the Brokers?

**Comment by hsun-cnnxty** [comment]
That's right. Kafka is moving in that direction to avoid the issue with ZK write performance.

**Comment by Poogles** [comment]
Any news on getting this merged?

**Comment by antoniogarrote** [comment]
Hi Paul, any thoughts about this PR?

We're using your library and this functionality would be very useful for us.

**Comment by pingles** [comment]
Ok- apologies all, it's taken me way too long to take a look.

I'm going to merge and release this as 0.3.4. I'll probably refactor the code a little but I can do that another time. Just be warned I may change some of the functions/signatures slightly :)

**Comment by pingles** [comment]
I've pushed 0.3.4 with this code to Clojars. Thanks for everyone's hard work (and patience)!

**Comment by Poogles** [comment]
Hero thanks.

**Pull request merged**
